apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: welcome-php
  name: welcome-php
  namespace: kapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome-php
  strategy: {}
  template:
    metadata:
      labels:
        app: welcome-php
        test: test2
    spec:
      containers:
      - image: quay.io/redhatworkshops/welcome-php
        name: welcome-php
        resources: {}
