---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 10s
  # ref:
  #   branch: master
  ref:
    tag: "6.3.6"
  url: https://github.com/stefanprodan/podinfo
